name: codio-publish
on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Render all mds
        uses: jayamanikharyono/jinja-action@v0.1
        with:
          datafile: .guides/template_data.json
          path: .guides/content/*.md

      - name: Publish to Codio
        uses: codio/codio-assignment-publish-action@publish-converter
        with:
          client-id: ${{ secrets.CODIO_CLIENT_ID }}
          secret-id: ${{ secrets.CODIO_SECRET_ID }}
          course-name: "automate master"
          assignment-name: "template-publish"
          changelog: "${{ github.event.head_commit.message }}"
          dir: ./
